//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumsRegistry.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlbumsRegistry.Core.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy album.
        /// </summary>
        public static string Albums_Index_Add {
            get {
                return ResourceManager.GetString("Albums_Index_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba albumów.
        /// </summary>
        public static string Albums_Index_Count {
            get {
                return ResourceManager.GetString("Albums_Index_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista albumów.
        /// </summary>
        public static string Albums_Index_Title {
            get {
                return ResourceManager.GetString("Albums_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        public static string General_Actions_Edit {
            get {
                return ResourceManager.GetString("General_Actions_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonawca.
        /// </summary>
        public static string General_Headers_Artist {
            get {
                return ResourceManager.GetString("General_Headers_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wytwórnia.
        /// </summary>
        public static string General_Headers_Publisher {
            get {
                return ResourceManager.GetString("General_Headers_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string General_Headers_Title {
            get {
                return ResourceManager.GetString("General_Headers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba nagrań.
        /// </summary>
        public static string General_Headers_TrackCount {
            get {
                return ResourceManager.GetString("General_Headers_TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok wydania.
        /// </summary>
        public static string General_Headers_Year {
            get {
                return ResourceManager.GetString("General_Headers_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista albumów.
        /// </summary>
        public static string Layout_AlbumsRegistry {
            get {
                return ResourceManager.GetString("Layout_AlbumsRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonawcy.
        /// </summary>
        public static string Layout_Artists {
            get {
                return ResourceManager.GetString("Layout_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wytwórnie.
        /// </summary>
        public static string Layout_Publishers {
            get {
                return ResourceManager.GetString("Layout_Publishers", resourceCulture);
            }
        }
    }
}
