//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumsRegistry.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlbumsRegistry.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd logowania!.
        /// </summary>
        public static string AdminMode_Activate_Error {
            get {
                return ResourceManager.GetString("AdminMode_Activate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string AdminMode_Activate_Password {
            get {
                return ResourceManager.GetString("AdminMode_Activate_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        public static string AdminMode_Activate_Return {
            get {
                return ResourceManager.GetString("AdminMode_Activate_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string AdminMode_Activate_Submit {
            get {
                return ResourceManager.GetString("AdminMode_Activate_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string AdminMode_Activate_Title {
            get {
                return ResourceManager.GetString("AdminMode_Activate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string AdminMode_Dectivate_Action {
            get {
                return ResourceManager.GetString("AdminMode_Dectivate_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy album.
        /// </summary>
        public static string Albums_Create_Title {
            get {
                return ResourceManager.GetString("Albums_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana danych albumu.
        /// </summary>
        public static string Albums_Edit_Title {
            get {
                return ResourceManager.GetString("Albums_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy album.
        /// </summary>
        public static string Albums_Index_Add {
            get {
                return ResourceManager.GetString("Albums_Index_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano nowy album.
        /// </summary>
        public static string Albums_Index_Added {
            get {
                return ResourceManager.GetString("Albums_Index_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba albumów.
        /// </summary>
        public static string Albums_Index_Count {
            get {
                return ResourceManager.GetString("Albums_Index_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista albumów.
        /// </summary>
        public static string Albums_Index_Title {
            get {
                return ResourceManager.GetString("Albums_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy wykonawca.
        /// </summary>
        public static string Artists_Create_Title {
            get {
                return ResourceManager.GetString("Artists_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana danych wykonawcy.
        /// </summary>
        public static string Artists_Edit_Title {
            get {
                return ResourceManager.GetString("Artists_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowego wykonawcę.
        /// </summary>
        public static string Artists_Index_Add {
            get {
                return ResourceManager.GetString("Artists_Index_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano nowego wykonawcę.
        /// </summary>
        public static string Artists_Index_Added {
            get {
                return ResourceManager.GetString("Artists_Index_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wykonawców.
        /// </summary>
        public static string Artists_Index_Count {
            get {
                return ResourceManager.GetString("Artists_Index_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonawcy.
        /// </summary>
        public static string Artists_Index_Title {
            get {
                return ResourceManager.GetString("Artists_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do listy.
        /// </summary>
        public static string General_Actions_BackToList {
            get {
                return ResourceManager.GetString("General_Actions_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        public static string General_Actions_Edit {
            get {
                return ResourceManager.GetString("General_Actions_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string General_Actions_Save {
            get {
                return ResourceManager.GetString("General_Actions_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj....
        /// </summary>
        public static string General_Actions_Search {
            get {
                return ResourceManager.GetString("General_Actions_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiany zostały zapisane.
        /// </summary>
        public static string General_ChangesSaved {
            get {
                return ResourceManager.GetString("General_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- wybierz --.
        /// </summary>
        public static string General_Dropdown_Select {
            get {
                return ResourceManager.GetString("General_Dropdown_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonawca.
        /// </summary>
        public static string General_Headers_Artist {
            get {
                return ResourceManager.GetString("General_Headers_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string General_Headers_City {
            get {
                return ResourceManager.GetString("General_Headers_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string General_Headers_Name {
            get {
                return ResourceManager.GetString("General_Headers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wytwórnia.
        /// </summary>
        public static string General_Headers_Publisher {
            get {
                return ResourceManager.GetString("General_Headers_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok wydania.
        /// </summary>
        public static string General_Headers_ReleaseYear {
            get {
                return ResourceManager.GetString("General_Headers_ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string General_Headers_Title {
            get {
                return ResourceManager.GetString("General_Headers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość pola może mieć max. 255 znaków.
        /// </summary>
        public static string General_Validation_ValueIsLimited {
            get {
                return ResourceManager.GetString("General_Validation_ValueIsLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość pola jest wymagana.
        /// </summary>
        public static string General_Validation_ValueIsRequired {
            get {
                return ResourceManager.GetString("General_Validation_ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista albumów.
        /// </summary>
        public static string Layout_AlbumsRegistry {
            get {
                return ResourceManager.GetString("Layout_AlbumsRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonawcy.
        /// </summary>
        public static string Layout_Artists {
            get {
                return ResourceManager.GetString("Layout_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wytwórnie.
        /// </summary>
        public static string Layout_Publishers {
            get {
                return ResourceManager.GetString("Layout_Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wytwórnia.
        /// </summary>
        public static string Publishers_Create_Title {
            get {
                return ResourceManager.GetString("Publishers_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana danych wytwórni.
        /// </summary>
        public static string Publishers_Edit_Title {
            get {
                return ResourceManager.GetString("Publishers_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nową wytwórnię.
        /// </summary>
        public static string Publishers_Index_Add {
            get {
                return ResourceManager.GetString("Publishers_Index_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano nową wytwórnię.
        /// </summary>
        public static string Publishers_Index_Added {
            get {
                return ResourceManager.GetString("Publishers_Index_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba wytwórni.
        /// </summary>
        public static string Publishers_Index_Count {
            get {
                return ResourceManager.GetString("Publishers_Index_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wytwórnie.
        /// </summary>
        public static string Publishers_Index_Title {
            get {
                return ResourceManager.GetString("Publishers_Index_Title", resourceCulture);
            }
        }
    }
}
